import { NextResponse } from "next/server"
import { createServerClient } from "@roadmapper/db"
import type { RoadmapResult } from "@roadmapper/schemas"

export async function GET(
  _request: Request,
  { params }: { params: { short_id: string } }
) {
  const db = createServerClient()

  const { data, error } = await db
    .from("roadmaps")
    .select("result_json")
    .eq("short_id", params.short_id)
    .eq("status", "complete")
    .maybeSingle()

  if (error || !data?.result_json) {
    return NextResponse.json({ error: "Roadmap not found" }, { status: 404 })
  }

  const roadmap = data.result_json as RoadmapResult

  const issues = roadmap.workflow_stages
    .sort((a, b) => a.stage_order - b.stage_order)
    .map((stage) => {
      const category = stage.category ?? "Build & Connect"
      const actionSteps = (stage as any).action_steps as string[] | undefined

      return {
        title: `[${category}] ${stage.stage_order}. ${stage.stage_name} — ${stage.best_overall_tool.name}`,
        body: [
          `## ${stage.stage_name}`,
          `**Phase:** ${category}`,
          "",
          `**Recommended tool:** [${stage.best_overall_tool.name}]`,
          `**Why:** ${stage.why_chosen}`,
          `**Estimated monthly cost:** $${stage.monthly_cost_estimate}`,
          `**Setup difficulty:** ${stage.setup_difficulty}`,
          `**Vendor lock-in risk:** ${stage.lock_in_risk}`,
          "",
          ...(actionSteps && actionSteps.length > 0
            ? ["**How to do this:**", ...actionSteps.map((s, i) => `${i + 1}. ${s}`), ""]
            : []),
          stage.cheapest_tool
            ? `**Budget alternative:** ${stage.cheapest_tool.name} — ${stage.cheapest_tool.why}`
            : "",
          stage.opensource_tool
            ? `**Open-source option:** ${stage.opensource_tool.name} — ${stage.opensource_tool.why}`
            : "",
          "",
          `---`,
          `_Generated by [AI Tool Roadmapper](https://roadmapper.ai/r/${params.short_id})_`,
        ]
          .filter((l) => l !== "")
          .join("\n"),
        labels: ["ai-stack", `phase:${category.toLowerCase().replace(/ & /g, "-")}`, `difficulty:${stage.setup_difficulty}`],
      }
    })

  return NextResponse.json(issues)
}
