import { NextResponse } from "next/server"
import { createServerClient } from "@roadmapper/db"
import type { RoadmapResult } from "@roadmapper/schemas"

function roadmapToMarkdown(roadmap: RoadmapResult, shortId: string): string {
  const lines: string[] = [
    `# AI Stack Roadmap: ${roadmap.business_type.replace(/_/g, " ").toUpperCase()}`,
    "",
    `> Generated by AI Tool Roadmapper | Share: https://roadmapper.ai/r/${shortId}`,
    "",
    `**Total monthly cost (best overall):** $${roadmap.total_monthly_cost_best_overall}`,
    `**Total monthly cost (cheapest):** $${roadmap.total_monthly_cost_cheapest}`,
    "",
    "---",
    "",
    "## Workflow Stages",
    "",
  ]

  for (const stage of roadmap.workflow_stages.sort((a, b) => a.stage_order - b.stage_order)) {
    lines.push(`### ${stage.stage_order}. ${stage.stage_name}`)
    lines.push("")
    lines.push(`**Best Tool:** ${stage.best_overall_tool.name} — $${stage.monthly_cost_estimate}/mo`)
    lines.push(`**Why:** ${stage.why_chosen}`)
    lines.push(`**Difficulty:** ${stage.setup_difficulty} | **Lock-in risk:** ${stage.lock_in_risk}`)
    if (stage.cheapest_tool) {
      lines.push(`**Cheaper alternative:** ${stage.cheapest_tool.name} — ${stage.cheapest_tool.why}`)
    }
    if (stage.opensource_tool) {
      lines.push(`**Open-source option:** ${stage.opensource_tool.name} — ${stage.opensource_tool.why}`)
    }
    lines.push("")
  }

  lines.push("## Build Sequence", "")
  for (const week of roadmap.build_sequence) {
    lines.push(`### Week ${week.week}: ${week.focus}`)
    lines.push(week.tools.map((t) => `- ${t}`).join("\n"))
    lines.push("")
  }

  return lines.join("\n")
}

export async function GET(
  _request: Request,
  { params }: { params: { short_id: string } }
) {
  const db = createServerClient()

  const { data, error } = await db
    .from("roadmaps")
    .select("result_json, short_id")
    .eq("short_id", params.short_id)
    .eq("status", "complete")
    .maybeSingle()

  if (error || !data?.result_json) {
    return NextResponse.json({ error: "Roadmap not found" }, { status: 404 })
  }

  const markdown = roadmapToMarkdown(data.result_json as RoadmapResult, data.short_id)

  return new Response(markdown, {
    headers: {
      "Content-Type": "text/markdown",
      "Content-Disposition": `attachment; filename="roadmap-${params.short_id}.md"`,
    },
  })
}
